### ISSUE TITLE
Doesn't work well for first answers

### ISSUE THREAD

**Issue by kevin-brown** [idmean/stacktextflow#1]
While it hides the original text area for adding new answers to questions with existing answers, it does not hide the text editor for first answers.

![image](https://cloud.githubusercontent.com/assets/1991850/5593433/db1c928a-91dc-11e4-92a6-6ae10d888012.png)

This was somewhat confusing at first, as I'm pretty sure it should always be hidden. ~~It also resulted in an alert being triggered when it was submitted, as the system thought I was just switching pages.~~

**Comment by idmean** [comment]
Actually it shouldn't be hiding anything. The hide method is in a comment (due to many bugs):
```
stacktextflowInjecter.iframe.insertBefore( $("#post-form")/* .hide() */ );
```

Are you sure you are using the latest commit?

**Comment by idmean** [comment]
What browser are you using?

**Comment by kevin-brown** [comment]
> Are you sure you are using the latest commit?

Latest, just cloned and installed it. GIt is telling me it's 88ce397.

> What browser are you using?

Chrome 39.0.2171.95 (x64 on Ubuntu)

**Comment by kevin-brown** [comment]
> Actually it shouldn't be hiding anything.

It just hit me that it's not actually hiding it, I momentarily forgot that the text editor is hidden after you have added your own post.
